export const SET_SELECT_VALUE = 'SET_SELECT_VALUE'

export const SET_SONG_LIST_HOTS = 'SET_SONG_LIST_HOTS'

export const SET_SONG_PLAY = 'SET_SONG_PLAY'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
